[package]
name = "nmp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
nmp-event-cache.workspace = true
nmp-observe.workspace = true
nmp-query.workspace = true
nmp-write-store.workspace = true
thiserror.workspace = true

[dev-dependencies]
nmp-event-cache-memory.workspace = true
nmp-query-standard.workspace = true
nmp-state.workspace = true
nmp-write.workspace = true
nmp-write-store-memory.workspace = true
nostr = { workspace = true, features = ["os-rng"] }
tokio.workspace = true

[lints]
workspace = true
