[package]
name = "fava-subscriptions-no-grouping"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
fava-relay.workspace = true
fava-state.workspace = true
fava-subscriptions.workspace = true
fava-wire.workspace = true
nostr.workspace = true

[dev-dependencies]
fava-query.workspace = true
nostr = { workspace = true, features = ["os-rng"] }

[lints]
workspace = true
