[package]
name = "fava-bookmarks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
nostr.workspace = true
fava-state.workspace = true
fava-write.workspace = true

[dev-dependencies]
nostr = { workspace = true, features = ["os-rng"] }

[lints]
workspace = true
