[package]
name = "fava-write-store-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
fava-query.workspace = true
fava-routing.workspace = true
fava-state.workspace = true
fava-write.workspace = true
fava-write-store.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
