[package]
name = "fava-routing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
nostr.workspace = true
fava-query.workspace = true
fava-relay.workspace = true
fava-state.workspace = true
fava-write.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
