[package]
name = "fava-write-store-redb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
nostr.workspace = true
fava-query.workspace = true
fava-routing.workspace = true
fava-relay.workspace = true
fava-state.workspace = true
fava-write.workspace = true
fava-write-store.workspace = true
redb.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
fava = { path = "../fava" }
fava-delivery-standard.workspace = true
fava-event-cache.workspace = true
fava-event-cache-memory.workspace = true
fava-publisher.workspace = true
fava-query-standard.workspace = true
fava-signer-local.workspace = true
fava-transport.workspace = true
nostr = { workspace = true, features = ["os-rng"] }

[lints]
workspace = true
