[package]
name = "fava-write-store-redb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
fava-query.workspace = true
fava-state.workspace = true
fava-write.workspace = true
fava-write-store.workspace = true
redb.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
nostr = { workspace = true, features = ["os-rng"] }

[lints]
workspace = true
