[package]
name = "fava-nip11"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
fava-publisher.workspace = true
fava-state.workspace = true
fava-subscriptions.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
