[package]
name = "fava-simple-groups"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"

[dependencies]
fava-query.workspace = true
fava-state.workspace = true
fava-write.workspace = true

[dev-dependencies]
nostr = { workspace = true, features = ["os-rng"] }

[lints]
workspace = true
