[package]
name = "fava-simple-groups"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"

[dependencies]
fava-query.workspace = true
fava-state.workspace = true
fava-write.workspace = true
nostr.workspace = true

[dev-dependencies]
fava = { path = "../fava" }
fava-delivery-standard.workspace = true
fava-nip29-management.workspace = true
fava-publisher-nip01.workspace = true
fava-query-standard.workspace = true
fava-signer-local.workspace = true
fava-subscriptions-no-grouping.workspace = true
fava-transport-websocket.workspace = true
fava-write-store-memory.workspace = true
nostr = { workspace = true, features = ["os-rng"] }
tokio = { workspace = true, features = ["net", "process", "rt-multi-thread"] }

[lints]
workspace = true
