[package]
name = "nmp-event-cache-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
nmp-event-cache.workspace = true
nmp-query.workspace = true
nmp-state.workspace = true
nostr.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
nostr = { workspace = true, features = ["os-rng"] }

[lints]
workspace = true
