[package]
name = "fava-subscriptions-standard"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
fava-state.workspace = true
fava-subscriptions.workspace = true
fava-transport.workspace = true
fava-wire.workspace = true
nostr.workspace = true
serde_json.workspace = true

[dev-dependencies]
fava-query.workspace = true
fava-subscriptions-no-grouping.workspace = true
fava-subscriptions-testkit.workspace = true
nostr = { workspace = true, features = ["os-rng"] }

[lints]
workspace = true
