[package]
name = "fava-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
nostr.workspace = true
fava-relay.workspace = true
fava-state.workspace = true
fava-wire.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
